artifact_location: file://C:\Users\prave\OneDrive\Desktop\MLOPS\Assignment\mlruns_1\504149296649114347
creation_time: 1716265556398
experiment_id: '504149296649114347'
last_update_time: 1716265556398
lifecycle_stage: active
name: Adversarial Training Experiment
